### ISSUE TITLE
Rengar 2.0 release checklist

### ISSUE THREAD

**Issue by teswayze** [teswayze/rengar#42]
- [x] Merge NNUE PR (#41)
- [x] Eigen is installed with a script instead of being clumsily checked in
- [x] Same for tests, and it’d be nice if they ran on windows
- [ ] #56
- [x] ~Add CI for ARM~ `macos-latest` runs on M1, which explains why BMI2 didn't work there
- [x] Release binary optimized for CCRL hardware
- [x] Update README
- [x] Clean up unused code
- [ ] #57
